name: Minimal setup
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Run benchmark
        run: go test -bench
          # Workflow will fail when an alert happens
          fail-on-alert: true
